# Chapter 4

## 4.1

In [2]:
# Load libraries
import numpy as np
from sklearn import preprocessing

# Create feature
feature = np.array(
    [
        [-500.5],
        [-100.1],
        [0],
        [100.1],
        [900.9]
    ]
)

# Create scaler
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))

# Scale feature
scaled_feature = minmax_scale.fit_transform(feature)

# Show feature
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

## 4.2

In [5]:
# Load libraries
import numpy as np
from sklearn import preprocessing

# Create feature
x = np.array(
    [
        [-1000.1],
        [-200.2],
        [500.5],
        [600.6],
        [9000.9]
    ]
)

# Create scaler
scaler = preprocessing.StandardScaler()

# Transform the feature
standardized = scaler.fit_transform((x))

# Show feature
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [6]:
# Print mean and standard deviation
print("Mean:", round(standardized.mean()))
print("Standard deviation:", standardized.std())

Mean: 0
Standard deviation: 1.0


In [7]:
# Create scaler
robust_scaler = preprocessing.RobustScaler()

# Transform feature
robust_scaler.fit_transform(x)

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])